### PR TITLE
Update and add config

### PR DESCRIPTION
**Pull request by HacKurx**
Hi Alexander,

Here are some updates and the addition of two distributions.

I let you choose ;)

Best regards,

### CODE REVIEW

**Comment by a13xp0p0v** [comment]
Hello @HacKurx,
Thanks for the update!
I'm merging it.

**Comment by a13xp0p0v** [comment]
@HacKurx, may I ask you to add/update information in the `links.txt` as well?
Thanks!

**Comment by HacKurx** [comment]
Hello @a13xp0p0v,

Thank's for the merge. Some configuration files do not have a url (debian, ubuntu, rhel), I had to extract the configuration from the kernel package.
I am willing to maintain all config occasionally.

**Comment by a13xp0p0v** [comment]
Nice, thanks!

I mean some of your new configs now have out-of-date links in `links.txt`.
For example, Alpine, Arch and Pentoo. Could you please update the links?

**Pull request merged**
