### PR TITLE
Add colors to output

### LINKED ISSUE #81: Color indicators for "check result" column
Would the maintainers be open to adding colors to the output of the "check result" column? For example, the output would be red for FAIL, and green for OK?

### PR DESCRIPTION
**Pull request by frakman1**
Shows OK in green and FAIL in red

image

fixes #81

### CODE REVIEW

**Comment by a13xp0p0v** [comment]
@frakman1, thanks for the pull request!

There are some small mistakes that break the tests.

Looking forward to your fixes.

**Comment by a13xp0p0v** [comment]
Hello @frakman1, the CI tests are broken again.

Please see, the argument of `colorize_result()` may be None in the verbose mode of the tool.
So we need to add something like that at the beginning of the function:
```
    if input is None:
        return input
```

Also please fix two pylint warnings added by this PR:

1) W0311: Bad indentation. Found 17 spaces, expected 16 (bad-indentation)

2) W0622: Redefining built-in 'input' (redefined-builtin).
To fix this, you need to rename the argument of the function.

Thanks again!
Looking forward to the fixes.

**Comment by frakman1** [comment]
I have never used pylint. Please share the syntax you used so I may reproduce the error.

**Comment by a13xp0p0v** [comment]
@frakman1, thanks for the fixes!

I think we should better add colors to the `stdout_result` in the unit tests instead of filtering them out before `assertEqual()`.

That would allow to test that `colorize_result()` works as expected.

**Comment by frakman1** [comment]
I'm sorry, this is outside the scope of my knowledge or effort. Not intersted in re-writing test cases.

**Review by a13xp0p0v — APPROVED** [review]
Ok, I'll adapt the test cases.

**Comment by frakman1** [comment]
Thank you!

**Comment by a13xp0p0v** [comment]
Added f8f7033.

Thanks for you contribution, @frakman1!

**Pull request merged**
